### ISSUE TITLE
combo cases is failing with weird error

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast-indicators#633]
I'll be able to take a closer look at this tomorrow, but just noting here for tracking: combo cases is failing with the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/krivard/projects/covid/auto/covidcast-indicators/combo_cases_and_deaths/delphi_combo_cases_and_deaths/__main__.py", line 11, in <module>
    run_module()  # pragma: no cover
  File "/home/krivard/projects/covid/auto/covidcast-indicators/combo_cases_and_deaths/delphi_combo_cases_and_deaths/run.py", line 163, in run_module
    df = combine_usafacts_and_jhu(signal, geo_res, extend_raw_date_range(params, sensor_name)) # pylint: disable=invalid-name
  File "/home/krivard/projects/covid/auto/covidcast-indicators/combo_cases_and_deaths/delphi_combo_cases_and_deaths/run.py", line 72, in combine_usafacts_and_jhu
    combined_df = combined_df.drop(["direction"], axis=1)
  File "/home/krivard/projects/covid/auto/covidcast-indicators/combo_cases_and_deaths/env/lib/python3.8/site-packages/pandas/core/frame.py", line 4167, in drop
    return super().drop(
  File "/home/krivard/projects/covid/auto/covidcast-indicators/combo_cases_and_deaths/env/lib/python3.8/site-packages/pandas/core/generic.py", line 3889, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/home/krivard/projects/covid/auto/covidcast-indicators/combo_cases_and_deaths/env/lib/python3.8/site-packages/pandas/core/generic.py", line 3923, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/home/krivard/projects/covid/auto/covidcast-indicators/combo_cases_and_deaths/env/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5287, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['direction'] not found in axis"
```

this started after I reinstalled to get the updated delphi_utils dependencies, so maybe it's related to a change in one of the other packages? did covidcast used to output direction and now it doesn't?

**Comment by capnrefsmmat** [comment]
> did covidcast used to output direction and now it doesn't?

yes

**Comment by chinandrew** [comment]
Yup. Opened #634
