### ISSUE TITLE
Combo cases/deaths producing duplicate geos

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast-indicators#910]
It seems that combo cases/deaths is pulling some geo ids from both usa-facts _and_ jhu-csse, which causes the archiver to balk. here's a sample file with duplicate geos:

```
$ for f in receiving/*.csv; do echo $f; cut -d, -f1 $f | sort | uniq -d; done 
[...]
receiving/20210227_county_confirmed_7dav_cumulative_num.csv
46000
46075
46107
46129
46135
```

Here's the error we get from archiver:

```
Traceback (most recent call last):
  File "/home/krivard/projects/covid/auto/covidcast-indicators/_delphi_utils_python/delphi_utils/archive.py", line 89, in diff_export_csv
    after_df_cmn = after_df.reindex(common_idx)
  File "/home/krivard/projects/covid/auto/covidcast-indicators/combo_cases_and_deaths/env/lib/python3.8/site-packages/pandas/util/_decorators.py", line 312, in wrapper
    return func(*args, **kwargs)
  File "/home/krivard/projects/covid/auto/covidcast-indicators/combo_cases_and_deaths/env/lib/python3.8/site-packages/pandas/core/frame.py", line 4176, in reindex
    return super().reindex(**kwargs)
  File "/home/krivard/projects/covid/auto/covidcast-indicators/combo_cases_and_deaths/env/lib/python3.8/site-packages/pandas/core/generic.py", line 4811, in reindex
    return self._reindex_axes(
  File "/home/krivard/projects/covid/auto/covidcast-indicators/combo_cases_and_deaths/env/lib/python3.8/site-packages/pandas/core/frame.py", line 4022, in _reindex_axes
    frame = frame._reindex_index(
  File "/home/krivard/projects/covid/auto/covidcast-indicators/combo_cases_and_deaths/env/lib/python3.8/site-packages/pandas/core/frame.py", line 4041, in _reindex_index
    return self._reindex_with_indexers(
  File "/home/krivard/projects/covid/auto/covidcast-indicators/combo_cases_and_deaths/env/lib/python3.8/site-packages/pandas/core/generic.py", line 4877, in _reindex_with_indexers
    new_data = new_data.reindex_indexer(
  File "/home/krivard/projects/covid/auto/covidcast-indicators/combo_cases_and_deaths/env/lib/python3.8/site-packages/pandas/core/internals/managers.py", line 1301, in reindex_indexer
    self.axes[axis]._can_reindex(indexer)
  File "/home/krivard/projects/covid/auto/covidcast-indicators/combo_cases_and_deaths/env/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3476, in _can_reindex
    raise ValueError("cannot reindex from a duplicate axis")
ValueError: cannot reindex from a duplicate axis
```

**Comment by chinandrew** [comment]
Hm I can't replicate this (admittedly on 3/2 to 3/11 data, which is what running the indicator locally gave me). Could you post the problematic file? Do we know if it's both usafacts/jhu or if it's a duplicate within usafacts (from bad geo mapping or some other bug)?

**Comment by krivard** [comment]
params:
```
{
  "common": {
    "log_exceptions": false,
    "export_dir": "./receiving",
    "log_filename": "delphi_combo_cases_and_deaths.log"
  },
  "indicator": {
    "export_start_date":[2020,4,1],
    "date_range":"all",
    "source":"indicator-combination",
    "wip_signal": ""
  }
}
```

Bad file:

[20210227_county_confirmed_7dav_cumulative_num.csv.zip](https://github.com/cmu-delphi/covidcast-indicators/files/6132045/20210227_county_confirmed_7dav_cumulative_num.csv.zip)

**Comment by dshemetov** [comment]
Hm, I thought this would concern Puerto Rico, since we changed that recently, but it's not
```
>>> df = pd.read_csv("20210227_county_confirmed_7dav_cumulative_num.csv")
>>> df
    geo_id          val  se  sample_size
0    21033  1333.857143 NaN          NaN
1    46000   161.285714 NaN          NaN
2    46000     4.714286 NaN          NaN
3    46075    84.857143 NaN          NaN
4    46075    85.000000 NaN          NaN
5    46107   368.857143 NaN          NaN
6    46107   369.142857 NaN          NaN
7    46129   677.000000 NaN          NaN
8    46129   719.428571 NaN          NaN
9    46135  2679.571429 NaN          NaN
10   46135  2793.285714 NaN          NaN
11   54087   493.000000 NaN          NaN
```

**Comment by krivard** [comment]
ohhhhhhh Andrew and I have figured this out; it's because we switched a couple days ago to requesting just the last week's worth of issues. So what's probably happening is that there were multiple issues of 46000 in the past week, but we're not dropping the spares.
