### ISSUE TITLE
Validator fails while looking for 'direction' column

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/covidcast-indicators#985]
From this morning's hhs_hosp run:

```
env/bin/python -m delphi_utils.validator --dry_run
[...]
Traceback (most recent call last):
  File "/home/indicators/.pyenv/versions/3.8.2/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/indicators/.pyenv/versions/3.8.2/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/mnt/data2/indicators/runtime/hhs_hosp/env/lib/python3.8/site-packages/delphi_utils/validator/datafetcher.py", line 169, in get_one_api_df
    geo_sig_api_df_or_error = fetch_api_reference(
  File "/mnt/data2/indicators/runtime/hhs_hosp/env/lib/python3.8/site-packages/delphi_utils/validator/datafetcher.py", line 129, in fetch_api_reference
    api_df = covidcast.signal(
  File "/mnt/data2/indicators/runtime/hhs_hosp/env/lib/python3.8/site-packages/covidcast/covidcast.py", line 189, in signal
    out.drop("direction", axis=1, inplace=True)
  File "/mnt/data2/indicators/runtime/hhs_hosp/env/lib/python3.8/site-packages/pandas/core/frame.py", line 4308, in drop
    return super().drop(
  File "/mnt/data2/indicators/runtime/hhs_hosp/env/lib/python3.8/site-packages/pandas/core/generic.py", line 4153, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/mnt/data2/indicators/runtime/hhs_hosp/env/lib/python3.8/site-packages/pandas/core/generic.py", line 4188, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/mnt/data2/indicators/runtime/hhs_hosp/env/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 5591, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['direction'] not found in axis"
```

I have a patch in production that will keep this error from blocking archiving until the next prod push, but we should try to fix it before then.

**Comment by chinandrew** [comment]
is this fixed with the updated flask code in https://github.com/cmu-delphi/delphi-epidata/pull/478?

**Comment by krivard** [comment]
Yes! thanks.
